// Code generated by protoc-gen-zig
 ///! package auth
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;

pub const UserDetailsRequest = struct {
    username: ManagedString = .Empty,

    pub const _desc_table = .{
        .username = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const UserDetailsResponse = struct {
    is_active: bool = false,
    apps: ArrayList(ManagedString),

    pub const _desc_table = .{
        .is_active = fd(1, .{ .Varint = .Simple }),
        .apps = fd(2, .{ .List = .String}),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
